"""Initial schema: calls and call_packets tables

Revision ID: a708dd915c92
Revises: 
Create Date: 2026-02-03 16:23:21.141620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a708dd915c92'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('call_id', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'COMPLETED', 'PROCESSING_AI', 'FAILED', 'ARCHIVED', name='callstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('expected_sequence', sa.Integer(), nullable=False),
    sa.Column('total_packets', sa.Integer(), nullable=False),
    sa.Column('missing_packets', sa.Text(), nullable=False),
    sa.Column('transcription', sa.Text(), nullable=True),
    sa.Column('sentiment', sa.String(length=50), nullable=True),
    sa.Column('ai_processing_attempts', sa.Integer(), nullable=False),
    sa.Column('ai_processed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_call_status_updated', 'calls', ['status', 'updated_at'], unique=False)
    op.create_index(op.f('ix_calls_call_id'), 'calls', ['call_id'], unique=True)
    op.create_index(op.f('ix_calls_id'), 'calls', ['id'], unique=False)
    op.create_table('call_packets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('call_id', sa.String(length=100), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.Float(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.call_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_call_sequence', 'call_packets', ['call_id', 'sequence'], unique=False)
    op.create_index(op.f('ix_call_packets_call_id'), 'call_packets', ['call_id'], unique=False)
    op.create_index(op.f('ix_call_packets_id'), 'call_packets', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_call_packets_id'), table_name='call_packets')
    op.drop_index(op.f('ix_call_packets_call_id'), table_name='call_packets')
    op.drop_index('idx_call_sequence', table_name='call_packets')
    op.drop_table('call_packets')
    op.drop_index(op.f('ix_calls_id'), table_name='calls')
    op.drop_index(op.f('ix_calls_call_id'), table_name='calls')
    op.drop_index('idx_call_status_updated', table_name='calls')
    op.drop_table('calls')
    # ### end Alembic commands ###
